
//GET USER_ACTIONS
export const USER_FETCH_LOADING = 'USER_FETCH_LOADING';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_FETCH_ERROR = 'USER_FETCH_ERROR';

//GET SINGLE USER_ACTIONS
export const FETCH_SINGLE_USER_LOADING = 'FETCH_SINGLE_USER_LOADING';
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS';
export const FETCH_SINGLE_USER_ERROR = 'FETCH_SINGLE_USER_ERROR';

//FILTER USER
export const FILTER_USERLIST = 'FILTER_USERLIST';